name: attendance_tracker
description: "Attendance Tracker"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  rename_app: ^1.6.2
  change_app_package_name: ^1.5.0
  cherry_toast: ^1.12.0
  dio: ^5.8.0+1
  validators: ^3.0.0
  loading_indicator: ^3.1.1
  flutter_svg: ^2.0.17
  url_launcher: ^6.3.1
  flutter_launcher_icons: ^0.14.3
  device_preview: ^1.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  build_runner: ^2.4.13
  hive_generator: ^2.0.1
  image_picker: ^1.1.2
  animated_custom_dropdown: ^3.1.1
  local_auth: ^2.3.0
  intl: ^0.19.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  google_sign_in: ^6.2.2
  firebase_storage: ^12.4.4
  cloud_firestore: ^5.6.5
  dio_cookie_manager: ^3.2.0
  cookie_jar: ^4.0.8
  cached_network_image: ^3.4.1
  supabase_flutter: ^2.8.4
  logger: ^2.5.0
  percent_indicator: ^4.2.4
  csv: ^6.0.0
  open_file: ^3.5.10
  file_picker: ^9.2.0
  date_picker_plus: ^4.1.0
  permission_handler: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/icons/


  fonts:
    - family: GothamBook
      fonts:
        - asset: assets/fonts/Gotham-Book.otf
